name: lint-backup

on:
  pull_request:

jobs:
  lint:
    if: false
    uses: charmbracelet/meta/.github/workflows/lint.yml@main
    with:
      golangci_path: .golangci.yml
      golangci_version: v2.4
      timeout: 10m
